name: CI
on:
  push:
    branches: [ main ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      -  name: List files (before checkout)
         run: ls-la

      -  name: Checkout code
         uses: actions/checkout@v4

      -  name: List files (after checkout)
         run: ls-la
