name: CI
on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      -  name: Checkout code
         uses: actions/checkout@v4

      -  name: Build and start services
         run: docker compose up -d --build

      -  name: Smoke test
         run: curl --fail --retry 10 --retry-delay 2 --retry-connrefused -s localhost:5000 | grep "visited"

      -  name: Show logs on failure
         if: failure()
         run: docker compose logs
