name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and start services
        run: docker compose up -d --build

      - name: Smoke test
        run: curl -sS --fail --retry 10 --retry-delay 2 --retry-all-errors localhost:5000 | grep "visited"

      - name: Show logs on failure
        if: failure()
        run: docker compose logs

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
         python-version: "3.11"

      - name: Install depedencies
        run: pip install -r requirements.txt pytest

      - name: Run unit tests
        run: pytest -v

      - name: Print python version in log
        if: always()
        run: python3 --version

  push:
    needs: [unit-test, test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/a-elef93/docker-hit-counter:latest
            ghcr.io/a-elef93/docker-hit-counter:${{ github.sha }}
